import {
  CATEGORY_LABELS,
  type Contribution,
  type CategoryScore,
  type ScoresResponse,
} from "@soteria/shared";
import { useCallback, useEffect, useId, useState } from "react";
import { Link } from "react-router-dom";

import { Button, Card, EmptyState, SparklineCard } from "../components";

/**
 * `/scores` — the five category scores and the overall score (US-17).
 *
 * The explanations behind each number are US-18's job; this page shows the
 * scores, says how many questions each came from, and flags anything provisional.
 * It deliberately does not invent a number where there is none: a category with
 * no answers renders an em dash, not a zero.
 *
 * The sparklines have a single point until US-19 lands the history query, so they
 * render as an empty chart rather than a fabricated trend. `SparklineCard`
 * already draws nothing for fewer than two points.
 */
const API_BASE = import.meta.env.VITE_API_URL ?? "";

function scoreLabel(category: CategoryScore): string {
  return category.score === null ? "—" : `${category.score}`;
}

/**
 * A "how to improve" hint for one contribution. This is the only new copy on
 * this page — every reason string is generated by the engine and shown verbatim.
 * The hints must agree with `docs/architecture/scoring.md`.
 */
interface ImprovementHint {
  text: string;
  to: string;
  linkLabel: string;
  /** Password and breach questions also get a privacy explainer link. */
  privacyLink?: boolean;
}

function hintFor(sourceId: string): ImprovementHint {
  if (sourceId.startsWith("pw_")) {
    return {
      text: "Check your passwords for reuse and length, then move them into a dedicated password manager.",
      to: "/password-tools",
      linkLabel: "Open the password tools",
      privacyLink: true,
    };
  }

  if (sourceId.startsWith("breach_")) {
    return {
      text: "Check your email against known breaches and give your important accounts their own passwords.",
      to: "/password-tools",
      linkLabel: "Check for breaches",
      privacyLink: true,
    };
  }

  if (sourceId.startsWith("mfa_")) {
    return {
      text: "Add an authenticator app or a hardware security key to your email and financial accounts.",
      to: "/questionnaire",
      linkLabel: "Update this answer",
    };
  }

  if (sourceId.startsWith("sw_")) {
    return {
      text: "Turn on automatic updates, stay on supported versions, and install software only from official sources.",
      to: "/questionnaire",
      linkLabel: "Update this answer",
    };
  }

  return {
    text: "Apply operating-system, phone and router updates within a day or two of release.",
    to: "/questionnaire",
    linkLabel: "Update this answer",
  };
}

/** The `no_cve_data` note: `delta` and `maxDelta` are both 0 — it is not an answer. */
function isNote(contribution: Contribution): boolean {
  return contribution.maxDelta === 0;
}

function ContributionItem({ contribution }: { contribution: Contribution }) {
  if (isNote(contribution)) {
    return (
      <li className="scores__contrib scores__contrib--note">
        <p className="scores__contrib-label">{contribution.label}</p>
        <p className="scores__contrib-reason">{contribution.reason}</p>
      </li>
    );
  }

  const best = contribution.delta === contribution.maxDelta;
  const hint = hintFor(contribution.sourceId);

  return (
    <li className="scores__contrib">
      <p className="scores__contrib-label">{contribution.label}</p>
      <p className="scores__contrib-points">
        {contribution.delta} of {contribution.maxDelta} points
      </p>
      <p className="scores__contrib-reason">{contribution.reason}</p>
      {best ? (
        <p className="scores__contrib-hint">
          This is already the strongest answer for this question.
        </p>
      ) : (
        <p className="scores__contrib-hint">
          {hint.text} <Link to={hint.to}>{hint.linkLabel}</Link>
          {hint.privacyLink ? (
            <>
              {" · "}
              <Link to="/learn/password-privacy">
                How these checks stay private
              </Link>
            </>
          ) : null}
        </p>
      )}
    </li>
  );
}

function CategoryDisclosure({ category }: { category: CategoryScore }) {
  const [open, setOpen] = useState(false);
  const panelId = useId();

  if (category.contributions.length === 0) return null;

  return (
    <div className="scores__disclosure">
      <button
        type="button"
        className="sot-btn sot-btn--secondary scores__disclosure-toggle"
        aria-expanded={open}
        aria-controls={panelId}
        onClick={() => setOpen((wasOpen) => !wasOpen)}
      >
        {open ? "Hide" : "Show"} how this score is calculated
      </button>
      <div id={panelId} className="scores__contribs" hidden={!open}>
        <ul className="scores__contrib-list">
          {category.contributions.map((contribution) => (
            <ContributionItem
              key={contribution.sourceId}
              contribution={contribution}
            />
          ))}
        </ul>
      </div>
    </div>
  );
}

function whyFor(category: CategoryScore): string {
  if (category.score === null) {
    return `Not answered yet — ${category.total} question${category.total === 1 ? "" : "s"} to go`;
  }

  const counted = `${category.answered} of ${category.total} answered`;

  return category.provisional ? `${counted} · provisional` : counted;
}

export default function Scores() {
  const [scores, setScores] = useState<ScoresResponse | null>(null);
  const [error, setError] = useState<string | null>(null);
  const [loading, setLoading] = useState(true);

  const load = useCallback(() => {
    setLoading(true);
    setError(null);

    fetch(`${API_BASE}/api/scores`, { credentials: "include" })
      .then((response) => {
        if (!response.ok) throw new Error(`HTTP ${response.status}`);
        return response.json() as Promise<ScoresResponse>;
      })
      .then(setScores)
      .catch(() => setError("Your scores could not be loaded right now."))
      .finally(() => setLoading(false));
  }, []);

  useEffect(load, [load]);

  if (loading) {
    return (
      <div className="scores">
        <h1>Your posture score</h1>
        <p role="status">Loading your scores…</p>
      </div>
    );
  }

  if (error !== null) {
    return (
      <div className="scores">
        <h1>Your posture score</h1>
        <p className="scores__error" role="alert">
          {error}
        </p>
        <Button variant="secondary" onClick={load}>
          Try again
        </Button>
      </div>
    );
  }

  if (scores === null || scores.overall === null) {
    return (
      <div className="scores">
        <h1>Your posture score</h1>
        <EmptyState
          title="No score yet"
          body="Answer the posture questionnaire and your five category scores will appear here. You can stop and resume at any point."
          action={<Link to="/questionnaire">Start the questionnaire</Link>}
        />
      </div>
    );
  }

  return (
    <div className="scores">
      <h1>Your posture score</h1>

      <Card title="Overall">
        <p className="scores__overall">
          <span className="scores__overall-value">{scores.overall}</span>
          <span className="scores__overall-of"> out of 100</span>
        </p>
        <p className="scores__lede">
          Scored from the questions you have answered, not from all of them, so
          an unfinished questionnaire is not counted against you.{" "}
          <Link to="/questionnaire">Answer more questions</Link> to sharpen it.
        </p>
        {scores.provisional ? (
          <p className="scores__note" role="note">
            One category is provisional: it will also account for known
            vulnerabilities in the software you list once that check is part of
            the product.
          </p>
        ) : null}
      </Card>

      <h2>By category</h2>
      <div className="scores__grid">
        {scores.categories.map((category) => (
          <SparklineCard
            key={category.key}
            name={CATEGORY_LABELS[category.key]}
            value={scoreLabel(category)}
            why={whyFor(category)}
            history={[]}
          >
            <CategoryDisclosure category={category} />
          </SparklineCard>
        ))}
      </div>

      {scores.updatedAt === null ? null : (
        <p className="scores__asof">
          Based on your answers saved on{" "}
          {new Date(scores.updatedAt).toLocaleDateString()}.
        </p>
      )}
    </div>
  );
}
