import { randomUUID } from "node:crypto";

import type { Scores } from "@soteria/shared";
import type { Knex } from "knex";

import { getDb } from "../db/knex.js";

/**
 * Persistence for computed category scores (`score_snapshots`).
 *
 * One row per category per submission, which is what US-19's history needs: a
 * single row holding all five would make "how did password hygiene move over six
 * months" a JSON query instead of an indexed one, and the table already carries
 * `(user_id, category, captured_at)` as an index for exactly that.
 *
 * What is deliberately NOT stored:
 *
 *  - the answers, which live in `questionnaire_responses` and are the source of
 *    truth. The engine is pure, so any score can be recomputed from them;
 *  - the contribution list. US-18's explanations are regenerated by calling the
 *    engine, not read back from here — storing prose would let a stored
 *    explanation drift out of step with the rules that produced it, and there is
 *    no column for it anyway.
 *
 * `rationale` holds a short, mechanical summary, never a free-text field a user
 * typed.
 */
export interface SnapshotRow {
  id: string;
  user_id: string;
  submission_id: string | null;
  category: string;
  score: number;
  rationale: string | null;
  captured_at: Date;
}

/** Fits `rationale`'s varchar(500) with room to spare. */
const RATIONALE_MAX = 400;

function rationaleFor(
  answered: number,
  total: number,
  provisional: boolean,
): string {
  const base = `${answered} of ${total} questions answered`;
  const note = provisional
    ? "; provisional, awaiting software vulnerability data"
    : "";

  return `${base}${note}`.slice(0, RATIONALE_MAX);
}

/**
 * Writes one row per scored category.
 *
 * Categories with a `null` score are skipped rather than stored as 0: `score` is
 * `NOT NULL`, and writing a 0 for "not answered yet" would put a false low point
 * into the history chart US-19 draws.
 *
 * Returns the number of rows written, so a caller can tell "nothing was
 * answered" from "the write failed".
 */
export async function writeScoreSnapshots(
  userId: string,
  submissionId: string | null,
  scores: Scores,
  db: Knex = getDb(),
  now = new Date(),
): Promise<number> {
  const rows: SnapshotRow[] = scores.categories
    .filter(
      (category): category is typeof category & { score: number } =>
        category.score !== null,
    )
    .map((category) => ({
      id: randomUUID(),
      user_id: userId,
      submission_id: submissionId,
      category: category.key,
      score: category.score,
      rationale: rationaleFor(
        category.answered,
        category.total,
        category.provisional,
      ),
      captured_at: now,
    }));

  if (rows.length === 0) return 0;

  await db("score_snapshots").insert(rows);

  return rows.length;
}
